export type Court = {
    id: string;
    name: string;
    location: string;
    address: string;
    neighborhood: string;
    city: string;
    sport: string;
    sports: string[];
    rating: number;
    reviewCount: number;
    price: number;
    oldPrice?: number;
    status: 'available' | 'busy' | 'closed' | any;
    frontendStatus?: 'available' | 'busy' | 'closed';
    badge?: string;
    amenities: string[];
    img: string;
    availableToday: boolean;
    openingHour: number;
    closingHour: number;
    unavailableDates: string[];
    capacity?: number;
    description?: string;
    type?: number;
    imageUrls?: string[];
    mainImageBase64?: string;
    imagesBase64?: string[];
    schedules?: OperatingDay[];
};

export type OperatingDay = {
    day: number; // 0-6 (Sunday-Saturday)
    openingHour: number;
    closingHour: number;
    isClosed: boolean;
};


export const SPORTS_LIST = [
    'Futebol Society',
    'Beach Tennis',
    'Vôlei de Praia',
    'Basquete',
    'Futsal',
    'Padel',
    'Tênis',
    'Handebol',
];

export const CITIES = ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'Curitiba', 'Porto Alegre'];

export const CATALOG_COURTS: Court[] = [
    {
        id: "1",
        name: 'Arena Central Paulista',
        location: 'São Paulo • Paulista',
        address: 'Avenida Paulista, 1578',
        neighborhood: 'Paulista',
        city: 'São Paulo',
        sport: 'Futebol Society',
        sports: ['Futebol Society', 'Futsal'],
        rating: 5.0,
        reviewCount: 312,
        price: 150,
        oldPrice: 200,
        status: 'available',
        badge: 'Melhor Avaliada',
        amenities: ['Vestiário', 'Estacionamento', 'Iluminação', 'Wifi'],
        img: 'https://images.unsplash.com/photo-1529900748604-07564a03e7a6?auto=format&fit=crop&w=800&q=80',
        availableToday: true,
        openingHour: 6,
        closingHour: 23,
        unavailableDates: ['2025-05-03','2025-05-10','2025-05-17','2025-05-24'],
    },
    {
        id: "2",
        name: 'Beach Club Sport',
        location: 'São Paulo • Morumbi',
        address: 'Avenida Giovanni Gronchi, 5930',
        neighborhood: 'Morumbi',
        city: 'São Paulo',
        sport: 'Beach Tennis',
        sports: ['Beach Tennis', 'Vôlei de Praia'],
        rating: 4.9,
        reviewCount: 218,
        price: 110,
        status: 'available',
        badge: 'Café da Manhã',
        amenities: ['Vestiário', 'Lanchonete', 'Wifi', 'Ducha'],
        img: 'https://images.unsplash.com/photo-1485395037613-e83d5c1f5ac4?auto=format&fit=crop&w=800&q=80',
        availableToday: true,
        openingHour: 7,
        closingHour: 22,
        unavailableDates: ['2025-05-05','2025-05-12','2025-05-19'],
    },
    {
        id: "3",
        name: 'Sport Center Sul',
        location: 'São Paulo • Santo André',
        address: 'Rua das Figueiras, 400',
        neighborhood: 'Santo André',
        city: 'São Paulo',
        sport: 'Basquete',
        sports: ['Basquete', 'Futsal', 'Handebol'],
        rating: 4.8,
        reviewCount: 145,
        price: 85,
        status: 'busy',
        badge: 'Reserva Antecipada',
        amenities: ['Estacionamento', 'Iluminação', 'Arquibancada'],
        img: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?auto=format&fit=crop&w=800&q=80',
        availableToday: false,
        openingHour: 8,
        closingHour: 21,
        unavailableDates: ['2025-05-01','2025-05-02','2025-05-08','2025-05-09','2025-05-15','2025-05-16'],
    },
    {
        id: "4",
        name: 'Quadra Premium Vila',
        location: 'São Paulo • Vila Olímpia',
        address: 'Rua Funchal, 200',
        neighborhood: 'Vila Olímpia',
        city: 'São Paulo',
        sport: 'Tênis',
        sports: ['Tênis', 'Padel'],
        rating: 4.7,
        reviewCount: 89,
        price: 130,
        status: 'available',
        amenities: ['Vestiário', 'Estacionamento', 'Academia', 'Wifi'],
        img: 'https://images.unsplash.com/photo-1502014822147-1aedfb0676e0?auto=format&fit=crop&w=800&q=80',
        availableToday: true,
        openingHour: 6,
        closingHour: 22,
        unavailableDates: ['2025-05-07','2025-05-14','2025-05-21'],
    },
    {
        id: "5",
        name: 'Padel Experience',
        location: 'Rio de Janeiro • Barra',
        address: 'Avenida das Américas, 4666',
        neighborhood: 'Barra da Tijuca',
        city: 'Rio de Janeiro',
        sport: 'Padel',
        sports: ['Padel', 'Tênis'],
        rating: 4.9,
        reviewCount: 276,
        price: 180,
        status: 'available',
        badge: 'Mais Reservado',
        amenities: ['Vestiário', 'Estacionamento', 'Lanchonete', 'Ducha', 'Wifi'],
        img: 'https://images.unsplash.com/photo-1554068865-24cecd4e34b8?auto=format&fit=crop&w=800&q=80',
        availableToday: true,
        openingHour: 7,
        closingHour: 23,
        unavailableDates: ['2025-05-04','2025-05-11','2025-05-18','2025-05-25'],
    },
    {
        id: "6",
        name: 'Vôlei Sunset',
        location: 'Rio de Janeiro • Ipanema',
        address: 'Avenida Vieira Souto, Posto 9',
        neighborhood: 'Ipanema',
        city: 'Rio de Janeiro',
        sport: 'Vôlei de Praia',
        sports: ['Vôlei de Praia', 'Beach Tennis'],
        rating: 4.6,
        reviewCount: 92,
        price: 70,
        status: 'closed',
        amenities: ['Ducha', 'Estacionamento'],
        img: 'https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?auto=format&fit=crop&w=800&q=80',
        availableToday: false,
        openingHour: 8,
        closingHour: 19,
        unavailableDates: ['2025-05-01','2025-05-02','2025-05-03','2025-05-04','2025-05-05','2025-05-06','2025-05-07','2025-05-08','2025-05-09','2025-05-10'],
    },
    {
        id: "7",
        name: 'Arena Futsal BH',
        location: 'Belo Horizonte • Centro',
        address: 'Avenida Afonso Pena, 1500',
        neighborhood: 'Centro',
        city: 'Belo Horizonte',
        sport: 'Futsal',
        sports: ['Futsal', 'Handebol'],
        rating: 4.5,
        reviewCount: 134,
        price: 60,
        status: 'available',
        amenities: ['Iluminação', 'Arquibancada'],
        img: 'https://images.unsplash.com/photo-1575361204480-aadea25e6e68?auto=format&fit=crop&w=800&q=80',
        availableToday: true,
        openingHour: 7,
        closingHour: 22,
        unavailableDates: ['2025-05-06','2025-05-13','2025-05-20'],
    },
    {
        id: "8",
        name: 'Clube Esportivo Sul',
        location: 'Porto Alegre • Moinhos',
        address: 'Rua Padre Chagas, 300',
        neighborhood: 'Moinhos de Vento',
        city: 'Porto Alegre',
        sport: 'Tênis',
        sports: ['Tênis', 'Padel', 'Beach Tennis'],
        rating: 4.8,
        reviewCount: 203,
        price: 120,
        oldPrice: 150,
        status: 'available',
        badge: 'Promoção',
        amenities: ['Vestiário', 'Piscina', 'Academia', 'Wifi', 'Estacionamento'],
        img: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=800&q=80',
        availableToday: true,
        openingHour: 6,
        closingHour: 23,
        unavailableDates: ['2025-05-02','2025-05-09','2025-05-16','2025-05-23'],
    },
    {
        id: "9",
        name: 'Top Court Curitiba',
        location: 'Curitiba • Batel',
        address: 'Avenida do Batel, 1868',
        neighborhood: 'Batel',
        city: 'Curitiba',
        sport: 'Futebol Society',
        sports: ['Futebol Society', 'Futsal'],
        rating: 4.7,
        reviewCount: 167,
        price: 95,
        status: 'busy',
        amenities: ['Vestiário', 'Iluminação', 'Estacionamento'],
        img: 'https://images.unsplash.com/photo-1529900748604-07564a03e7a6?auto=format&fit=crop&w=800&q=80',
        availableToday: false,
        openingHour: 7,
        closingHour: 22,
        unavailableDates: ['2025-05-01','2025-05-02','2025-05-03','2025-05-04','2025-05-05'],
    },
    {
        id: "10",
        name: 'Beach Park Arena',
        location: 'Rio de Janeiro • Leblon',
        address: 'Avenida Delfim Moreira, Posto 12',
        neighborhood: 'Leblon',
        city: 'Rio de Janeiro',
        sport: 'Beach Tennis',
        sports: ['Beach Tennis', 'Vôlei de Praia'],
        rating: 5.0,
        reviewCount: 411,
        price: 200,
        status: 'available',
        badge: 'Top 1 RJ',
        amenities: ['Vestiário', 'Ducha', 'Lanchonete', 'Wifi', 'Estacionamento', 'Academia'],
        img: 'https://images.unsplash.com/photo-1485395037613-e83d5c1f5ac4?auto=format&fit=crop&w=800&q=80',
        availableToday: true,
        openingHour: 6,
        closingHour: 22,
        unavailableDates: ['2025-05-08','2025-05-15','2025-05-22'],
    },
    {
        id: "11",
        name: 'Arena Handebol MG',
        location: 'Belo Horizonte • Savassi',
        address: 'Rua Pernambuco, 1000',
        neighborhood: 'Savassi',
        city: 'Belo Horizonte',
        sport: 'Handebol',
        sports: ['Handebol', 'Basquete', 'Futsal'],
        rating: 4.4,
        reviewCount: 58,
        price: 75,
        status: 'available',
        amenities: ['Iluminação', 'Arquibancada', 'Estacionamento'],
        img: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?auto=format&fit=crop&w=800&q=80',
        availableToday: true,
        openingHour: 8,
        closingHour: 21,
        unavailableDates: ['2025-05-05','2025-05-12','2025-05-19','2025-05-26'],
    },
    {
        id: "12",
        name: 'Quadra Park Curitiba',
        location: 'Curitiba • Água Verde',
        address: 'Avenida República Argentina, 500',
        neighborhood: 'Água Verde',
        city: 'Curitiba',
        sport: 'Basquete',
        sports: ['Basquete', 'Futsal'],
        rating: 4.6,
        reviewCount: 79,
        price: 80,
        status: 'closed',
        amenities: ['Iluminação', 'Vestiário'],
        img: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=800&q=80',
        availableToday: false,
        openingHour: 9,
        closingHour: 20,
        unavailableDates: ['2025-05-01','2025-05-02','2025-05-03','2025-05-04','2025-05-05','2025-05-06','2025-05-07'],
    },
];
