# docker-compose.override.yml

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    # Em dev, loga tudo
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
